<?php

namespace Brioche\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodeRepository extends EntityRepository
{
    public function findCode($code)
    {
        return $this->_em->createQueryBuilder()
                ->select('c, ct, b')
                ->from('BriocheCoreBundle:Code', 'c')
                ->leftJoin('c.codeType', 'ct')
                ->leftJoin('c.brioches', 'b')
                ->where('c.code = :code')
                ->setParameters(array(
                    ':code' => $code,
                ))
                ->getQuery()
                ->getOneOrNullResult()
        ;
    }
}
