<?php

namespace Brioche\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function findAllEnabledComments()
    {
        return $this->_em->createQueryBuilder()
                ->select('c')
                ->from('BriocheCoreBundle:Comment', 'c')
                ->where('c.disabled = false')
                ->orderBy('c.dateCreate', 'desc')
                ->getQuery()
                ->getResult()
        ;
    }
}
