<?php

namespace Brioche\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RoundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoundRepository extends EntityRepository
{
    public function findFuturesRounds()
    {
        $now = new \DateTime();
        
        return $this->_em->createQueryBuilder()
                ->select('r, b')
                ->from('BriocheCoreBundle:Round', 'r')
                ->leftJoin('r.brioches', 'b', 'with', 'b.validated = true')
                ->where('r.date >= :date')
                ->orderBy('r.date')
                ->setParameters(array(
                    ':date' => $now->modify('-4 days'),
                ))
                ->getQuery()
                ->getResult()
        ;
    }
    
    /**
     * Return round $id.
     * 
     * WARNING: always use this method to get a round
     * otherwise Round::getTotal() and Round::isAvailable() could return bad results
     * 
     * @param integer $id
     * @return \Brioche\CoreBundle\Entity\Round
     */
    public function findRound($id)
    {
        return $this->_em->createQueryBuilder()
                ->select('r, b')
                ->from('BriocheCoreBundle:Round', 'r')
                ->leftJoin('r.brioches', 'b', 'with', 'b.validated = true')
                ->where('r.id = :id')
                ->setParameters(array(
                    ':id' => $id,
                ))
                ->getQuery()
                ->getOneOrNullResult()
        ;
    }
}
