<?php

namespace Brioche\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RoundRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoundRepository extends EntityRepository
{
    public function findFuturesRounds()
    {
        return $this->_em->createQueryBuilder()
                ->select('r, b')
                ->from('BriocheCoreBundle:Round', 'r')
                ->leftJoin('r.brioches', 'b', 'with', 'b.validated = true')
                ->where('r.date >= :now')
                ->orderBy('r.date')
                ->setParameters(array(
                    ':now' => new \DateTime(),
                ))
                ->getQuery()
                ->getResult()
        ;
    }
}
