alcalyn_payplug:
    resource: "@AlcalynPayplugBundle/Resources/config/routing.yml"
    prefix:   /

phax:
    resource: "@PhaxCoreBundle/Resources/config/routing.yml"
    
brioche_core:
    resource: "@BriocheCoreBundle/Resources/config/routing.yml"
    prefix:   /

brioche_core_fosuser:
    resource: "@BriocheCoreBundle/Resources/config/routingFosUser.yml"
    prefix:   /
