security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: true

    access_control:

    providers:
        in_memory:
             memory:
                users:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
