services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
            
    twig.onpath:
        class: Brioche\CoreBundle\Twig\TwigOnPath
        arguments:
            - @request_stack
        tags:
            - { name: twig.extension }
