services:
    brioche_core.listeners.payment:
        class: Brioche\CoreBundle\EventListener\PaymentListener
        arguments: []
        tags:
            - { name: kernel.event_listener, event: event.payplug.ipn, method: onPayment }
