brioche_core_brioche_controller:
    resource: "@BriocheCoreBundle/Controller/BriocheController.php"
    type:     annotation

brioche_core_front_controller:
    resource: "@BriocheCoreBundle/Controller/FrontController.php"
    type:     annotation

brioche_core_command_controller:
    resource: "@BriocheCoreBundle/Controller/CommandController.php"
    type:     annotation

brioche_core_maillist_controller:
    resource: "@BriocheCoreBundle/Controller/MailListController.php"
    type:     annotation

brioche_core_comment_controller:
    resource: "@BriocheCoreBundle/Controller/CommentController.php"
    type:     annotation
