services:
    brioche_core.brioche_manager:
        class: Brioche\CoreBundle\Services\BriocheManager
        
    brioche_core.code_manager:
        class: Brioche\CoreBundle\Services\CodeManager
        
    brioche_core.brioche_builder:
        class: Brioche\CoreBundle\Services\BriocheBuilder
        arguments:
            - @doctrine.orm.entity_manager
            - @session
            - @brioche_core.brioche_manager
            - @brioche_core.code_manager
            - @brioche_core.flash_messages
        
    brioche_core.brioche_payment:
        class: Brioche\CoreBundle\Services\BriochePaymentService
        arguments: [@payplug.payment]
        
    brioche_core.brioche_ipn_service:
        class: Brioche\CoreBundle\Services\BriocheIPNService
        arguments: [@doctrine.orm.entity_manager, @brioche_core.mail_factory]
        
    brioche_core.mail_factory:
        class: Brioche\CoreBundle\Services\MailFactory
        arguments: [@templating, @swiftmailer.mailer]
        
    brioche_core.mail_list:
        class: Brioche\CoreBundle\Services\MailListService
        arguments: [@form.factory]
        
    brioche_core.flash_messages:
        class: Brioche\CoreBundle\Services\FlashMessages
        arguments: [@session]
