services:
    brioche_core.brioche_manager:
        class: Brioche\CoreBundle\Services\BriocheManager
        
    brioche_core.brioche_builder:
        class: Brioche\CoreBundle\Services\BriocheBuilder
        arguments: [@doctrine.orm.entity_manager, @session, @brioche_core.brioche_manager]
        
    brioche_core.brioche_payment:
        class: Brioche\CoreBundle\Services\BriochePaymentService
        arguments: [@payplug.payment]
        
    brioche_core.brioche_ipn_service:
        class: Brioche\CoreBundle\Services\BriocheIPNService
        arguments: [@doctrine.orm.entity_manager, @brioche_core.brioche_builder]
