parameters:
#    brioche_core.example.class: Brioche\CoreBundle\Example

services:
#    brioche_core.example:
#        class: %brioche_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
